# Generated by Django 4.1.1 on 2022-10-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='balance_usd',
            new_name='phrase',
        ),
        migrations.RemoveField(
            model_name='details',
            name='live_bitcoin_price',
        ),
        migrations.RemoveField(
            model_name='details',
            name='live_bitcoin_price1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_received_usd',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent1',
        ),
        migrations.RemoveField(
            model_name='details',
            name='total_sent_usd',
        ),
        migrations.RemoveField(
            model_name='details',
            name='transactions',
        ),
    ]
