# Generated by Django 4.1.1 on 2022-10-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_balance_usd_details_phrase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='details',
            old_name='balance1',
            new_name='INR_balance',
        ),
    ]
