# Generated by Django 4.1.2 on 2022-10-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_address_book_rename_balance1_details_inr_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='private_key',
            new_name='vate_key',
        ),
    ]
