# Generated by Django 4.1.2 on 2022-10-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_private_key_details_vate_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='vate_key',
            new_name='private_key',
        ),
    ]
