# Generated by Django 4.1.2 on 2022-10-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_vate_key_details_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_book',
            old_name='Name',
            new_name='bit_id',
        ),
    ]
