# Generated by Django 4.1.2 on 2022-10-23 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_rename_name_address_book_bit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='create_at',
            field=models.DateTimeField(auto_created=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='details',
            name='is_verified',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='token',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
