# Generated by Django 4.1.2 on 2022-10-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_details_create_at_details_email_details_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='details',
            name='token',
        ),
        migrations.RemoveField(
            model_name='details',
            name='user',
        ),
    ]
