# Generated by Django 4.1.2 on 2022-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_profile_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=500)),
                ('INR_balance', models.CharField(max_length=500)),
                ('private_key', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phrase', models.CharField(max_length=500)),
            ],
        ),
    ]
